// Barrel exports for clean imports (Open/Closed Principle)
export { default as Header } from './header'
export { default as HeroSection } from './hero-section'
export { default as BenefitsSection, BenefitCard } from './benefits-section'
export { default as MonstersSection, MonsterCard } from './monsters-section'
export { default as ActionsSection, ActionCard } from './actions-section'
export { default as NewsletterSection } from './newsletter-section'
export { default as Footer } from './footer'
export { default as WalletDisplay } from './wallet-display'
export { default as PageHeaderWithWallet } from './page-header-with-wallet'
export { default as TomatokenIcon } from './tomatoken-icon'
